### ISSUE TITLE
SCSS $include not working

### ISSUE THREAD

**Issue by herkulano** [mrmlnc/vscode-csscomb#13]
Sort order is not working properly for $include:
```json
"sort-order": [
      [ "$variable" ],
      [ "$include" ],
      [ "..." ],
      [ "$include mq" ]
    ]
```

Should output to:
```scss
.class {
  @include some-function();

  // styles...

  @include mq(mobile, tablet) {
    // styles...
  }
}
```

Instead outputs to:
```scss
.class {
  @include some-function();
  @include mq(mobile, tablet) {
    // styles...
  }

  // styles...
}
```

**Comment by mrmlnc** [comment]
Hello, @herkulano,

First, thanks for you report.

Unfortunately, this is not a problem of this extension. Since the described situation is reproduced in Sublime Text is a problem CSSComb Core.  I will update the plugin, once this issue is resolved in CSSComb.

**Comment by herkulano** [comment]
@mrmlnc thanks for the thorough answer. I'll report it in csscomb, if not reported already.

**Comment by oskarols** [comment]
According to https://github.com/csscomb/csscomb.js/issues/437 this feature is only included in 4.0, and looking at the package.json for vscode-csscomb it seems it's _not_ using 4.0.

Would it be possible to bumb the version to 4.0 to get this feature?

**Comment by mrmlnc** [comment]
@oskarols, I think yes. Just one question: current alpha version is stable?

I wouldn't want to disappoint those users that use `vscode-csscomb` at work.

**Comment by mrmlnc** [comment]
Fixed in version `2.0.0`. Please, try new version of this extension.

**Comment by ajtroxell** [comment]
I've got all of my CSSComb settings within my settings.json so that it applies globally to all of my open projects, but this functionality still does not seem to work. I have as follows:
![image](https://cloud.githubusercontent.com/assets/3221144/20433508/8970b10a-ad69-11e6-95b2-f93148de83f0.png)

But my output is still:
![image](https://cloud.githubusercontent.com/assets/3221144/20433518/996ff58e-ad69-11e6-8899-a08a69d78bf6.png)

**Comment by mrmlnc** [comment]
Hello, @ajtroxell,

You try to use `useLatestCore` options?

**Comment by ajtroxell** [comment]
Now i get `TypeError: Cannot read property 'is' of null`
